
name: colemaket
description: ColeMarket - Compra/venta de uniformes escolares
publish_to: "none"
version: 0.0.2+2

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1   # (o la última 2.x estable)
  go_router: ^14.2.0
  intl: ^0.20.2
  google_fonts: ^6.2.1
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  uuid: ^4.5.1
  cached_network_image: ^3.3.1
  state_notifier: ^1.0.0
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
